---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter: postgres
  database: imagewiki
  username: imagewiki
  password: imagewiki
  host: localhost
  log_stream: log/logging.sql
  log_level: 0 

production:
  <<: *defaults

rake:
  <<: *defaults

